### ISSUE TITLE
The game gets stuck in "Login" charge screen (Stepmania Outfox Alpha 4.9.10 Mac Version) 

### ISSUE THREAD

**Issue by MrXD06** [Curilang/DDR-A#2]
i don't know why this happen, but it gets stuck in the charging screen
Pls help, i really want to use this theme

**Comment by MrXD06** [comment]
![image](https://user-images.githubusercontent.com/81484776/131938733-67664938-50c5-4683-a567-0fcd802f7de8.png)

**Comment by Curilang** [comment]
It is for the Region.lua file, but the Region.lua file in Themes folder

**Comment by MrXD06** [comment]
One thing, your natural language is spanish?

**Comment by Curilang** [comment]
Yes, why?

**Comment by MrXD06** [comment]
El mio tambien, buena

**Comment by MrXD06** [comment]
Pero, ya modifiqué el Region.lua y lo puse en la carpeta themes

**Comment by MrXD06** [comment]
No funciona

**Comment by MrXD06** [comment]
![image](https://user-images.githubusercontent.com/81484776/132059683-df8436b2-2fb8-401d-be94-80ce249c2d23.png)
bruh, intente poniendo Region.lua en la otra carpeta llamada Themes y funciono.
Igual gracias por todo.
